# Generated by Django 3.1.6 on 2022-09-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='points',
            field=models.IntegerField(default=500),
        ),
    ]
