# Generated by Django 3.1.6 on 2022-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='has_team',
            field=models.BooleanField(default=False),
        ),
    ]
