# Generated by Django 3.1.6 on 2022-09-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cuser_has_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
