# Generated by Django 3.1.6 on 2022-09-18 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0002_team_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='team',
            name='teammate2',
            field=models.ManyToManyField(limit_choices_to=2, to=settings.AUTH_USER_MODEL),
        ),
    ]
