# Generated by Django 3.1.6 on 2022-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20220918_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teammate2',
        ),
        migrations.RemoveField(
            model_name='team_request',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='team',
            name='joueur1',
            field=models.CharField(default='lel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='joueur2',
            field=models.CharField(default='lel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_request',
            name='joueur1',
            field=models.CharField(default='lel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_request',
            name='joueur2',
            field=models.CharField(default='lel', max_length=50),
            preserve_default=False,
        ),
    ]
