# Generated by Django 3.1.6 on 2022-09-19 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0004_auto_20220918_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='joueur1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='joueur2',
        ),
        migrations.RemoveField(
            model_name='team_request',
            name='joueur1',
        ),
        migrations.RemoveField(
            model_name='team_request',
            name='joueur2',
        ),
        migrations.AddField(
            model_name='team',
            name='joueurs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team_request',
            name='joueurs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
