# Generated by Django 3.1.6 on 2022-09-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20220919_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_request',
            name='demandeur',
            field=models.CharField(default='', max_length=50),
        ),
    ]
