# Generated by Django 3.1.6 on 2022-09-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_team_request_demandeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_request',
            name='demandé',
            field=models.CharField(default='', max_length=50),
        ),
    ]
