# Generated by Django 3.1.6 on 2022-09-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_team_request_demandé'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='joueur1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='joueur2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
