# Generated by Django 3.1.6 on 2022-09-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_auto_20220920_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
