# Generated by Django 3.1.6 on 2022-09-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0008_auto_20220920_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_passé',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('victoire', models.CharField(max_length=50)),
                ('teams', models.ManyToManyField(to='profil.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match_a_venir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('teams', models.ManyToManyField(to='profil.Team')),
            ],
        ),
    ]
