# Generated by Django 3.1.6 on 2022-09-22 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_team_rank'),
        ('matchs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_a_venir',
            name='date',
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 10, 49, 47, 941004)),
        ),
        migrations.CreateModel(
            name='Match_en_cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 22, 10, 49, 47, 942001))),
                ('teams', models.ManyToManyField(to='profil.Team')),
            ],
        ),
    ]
