# Generated by Django 3.1.6 on 2022-09-22 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0002_auto_20220922_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 5, 11, 242545)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 5, 11, 241546)),
        ),
    ]
