# Generated by Django 3.1.6 on 2022-09-22 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0003_auto_20220922_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_a_venir',
            old_name='team1',
            new_name='demandeur',
        ),
        migrations.RenameField(
            model_name='match_a_venir',
            old_name='team2',
            new_name='demandé',
        ),
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 52, 11, 553412)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 52, 11, 553412)),
        ),
    ]
