# Generated by Django 3.1.6 on 2022-09-22 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0004_auto_20220922_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_passé',
            old_name='team1',
            new_name='defaite',
        ),
        migrations.RemoveField(
            model_name='match_passé',
            name='team2',
        ),
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 12, 14, 1, 709877)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 12, 14, 1, 708878)),
        ),
    ]
