# Generated by Django 3.1.6 on 2022-09-22 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0005_auto_20220922_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 12, 14, 33, 497587)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 12, 14, 33, 496620)),
        ),
    ]
