# Generated by Django 3.1.6 on 2022-09-22 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0006_auto_20220922_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_en_cours',
            name='victoire',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 15, 50, 14, 582560)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 15, 50, 14, 581559)),
        ),
    ]
