# Generated by Django 3.1.6 on 2022-09-22 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0007_auto_20220922_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_passé',
            name='pts_defaits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_passé',
            name='pts_gagnants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 20, 24, 26, 836976)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 20, 24, 26, 836976)),
        ),
    ]
