# Generated by Django 3.1.6 on 2022-09-23 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0008_auto_20220922_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 13, 43, 23, 68019)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 13, 43, 23, 52368)),
        ),
    ]
