# Generated by Django 4.1.1 on 2022-09-27 19:38

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchs', '0009_auto_20220923_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_passé',
            name='joueur_defait1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match_passé',
            name='joueur_defait2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match_passé',
            name='joueur_victorieux1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match_passé',
            name='joueur_victorieux2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match_passé',
            name='joueurs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 21, 38, 10, 639049)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 21, 38, 10, 639049)),
        ),
    ]
