# Generated by Django 4.1.1 on 2022-09-27 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0010_match_passé_joueur_defait1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_passé',
            name='teams',
        ),
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 21, 44, 12, 915610)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 21, 44, 12, 915610)),
        ),
    ]
