# Generated by Django 4.1.1 on 2022-09-27 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0011_remove_match_passé_teams_alter_match_en_cours_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_en_cours',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 22, 17, 28, 776599)),
        ),
        migrations.AlterField(
            model_name='match_passé',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 27)),
        ),
    ]
